/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicios_resueltos_actividad3;

/**
 *
 * @author User
 */
public class EjercicioPropuesto19 extends javax.swing.JFrame {

    /**
     * Creates new form EjercicioPropuesto19
     */
    public EjercicioPropuesto19() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCalcular19 = new javax.swing.JButton();
        btnBorrar19 = new javax.swing.JButton();
        btnSalir19 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Lado19 = new javax.swing.JTextField();
        Salida19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCalcular19.setText("Calcular");
        btnCalcular19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular19ActionPerformed(evt);
            }
        });

        btnBorrar19.setText("Borrar");
        btnBorrar19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar19ActionPerformed(evt);
            }
        });

        btnSalir19.setText("Salir");
        btnSalir19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir19ActionPerformed(evt);
            }
        });

        jLabel1.setText("Ejercicio Propuesto 19: Triángulo Equilatero");

        jLabel2.setText("Lado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addComponent(Lado19, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Salida19)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCalcular19)
                                .addGap(34, 34, 34)
                                .addComponent(btnBorrar19)
                                .addGap(46, 46, 46)
                                .addComponent(btnSalir19)))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Lado19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular19)
                    .addComponent(btnBorrar19)
                    .addComponent(btnSalir19))
                .addGap(18, 18, 18)
                .addComponent(Salida19)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcular19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular19ActionPerformed
        double lado, perimetro, area, altura;
        lado = Double.parseDouble(Lado19.getText());
        perimetro = Math.round(Operador.perimetroTriangulo(lado));
        altura = Math.round(Operador.alturaTriangulo(lado));
        area = Math.round(Operador.areaTriangulo(lado, altura));
        
        String salida = "El perímetro del triángulo es: " + perimetro + ", su altura: " + altura + " y su área: " + area;
        
        Salida19.setText(String.valueOf(salida));
    }//GEN-LAST:event_btnCalcular19ActionPerformed

    private void btnSalir19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir19ActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalir19ActionPerformed

    private void btnBorrar19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar19ActionPerformed
        Lado19.setText("");
        Salida19.setText("");        
    }//GEN-LAST:event_btnBorrar19ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjercicioPropuesto19.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjercicioPropuesto19.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjercicioPropuesto19.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjercicioPropuesto19.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EjercicioPropuesto19().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Lado19;
    private javax.swing.JLabel Salida19;
    private javax.swing.JButton btnBorrar19;
    private javax.swing.JButton btnCalcular19;
    private javax.swing.JButton btnSalir19;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
